### ISSUE TITLE
Anzeige: Wer ist im Büro?

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#10]
Als User 
möchte ich während des Buchungsprozesses eines Arbeitsplatzes sehen, welche Mitarbeiter sich zu meiner Wunschzeit in den umliegenden Arbeitsplätzen der ausgewählten Etage eingebucht haben, 
sodass ich meinen bevorzugten Arbeitsplatz auswählen kann.
    
Im Buchungsprozess während der Anzeige und Auswahl des Arbeitsplatzes [zu einem ausgewählten Zeitraum] soll dem Nutzer angezeigt werden, welche Plätze (zu welchen Zeiten?) von welchen Mitarbeiter/n gebucht ist. Gleiches soll für das gesamte Stockwerk angezeigt werden. Die bereits gebuchten Plätze sind für den Nutzer nicht mehr buchbar.

**Comment by PhilippFaber** [comment]
Die Übersichtsseite, wer sich zu einem bestimmten Zeitpunkt im Büro befindet, wird an mehreren Punkten innerhalb der Anwendung benötigt.

1. Während des Buchungsvorganges, damit man anzeigen kann welche Arbeitsplätze für ein Datum noch nicht reserviert wurden.
2. Als Dashboard für den User, damit man sieht, wer zum aktuellen Zeitpunkt einen Arbeitsplatz reserviert hat.
3. Als allgemeines Dashboard für den Eingangsbereich der Bürofläche (optionales Feature)

Im Backend muss eine Möglichkeit erstellt werden, eine Übersicht eines Stockwerkes zu liefern, die basierend auf einem Datum die passenden Reservierungen zurückliefert.
Diese Aufgabe hat Berührungspunkte mit #6.

**Comment by djfhe** [comment]
Closed by #100
