### ISSUE TITLE
Sorting von buchbaren Arbeitsplätzen

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#102]
Als Administrator möchte ich buchbare Arbeitsplätze sortieren können, damit sie beim Nutzer in einer bestimmten Reihenfolge angezeigt werden.

Akzeptanzkriterium:
- [x] Buchbare Arbeitsplätze verfügen über eine Reihenfolge
- [x] Beim Nutzer werden die Arbeitsplätze in dieser Reihenfolge sortiert angezeigt
- [x] Der Administrator kann diese Reihenfolge editieren

Vorschlag:
https://material.angular.io/cdk/drag-drop/overview#reordering-lists

**Comment by MigueLozano** [comment]
https://user-images.githubusercontent.com/11196461/221645494-01a078e8-1f56-4943-81f8-8c60ce63045b.mp4
