### ISSUE TITLE
Deplyoment für Staging Server

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#107]
Als Systemadministrator will ich im Jenkins den Dev-Branch auf einen staging Server deployen können, um ein gemeinsames Testingsystem für Kunde und Entwickler anzubieten.

Akzeptanzkriterium:
- [x] Der Dev Branch wird über Jenkins auf ein Staging Server deployed
- [x] Auf diesen Staging Server haben sowohl Entwickler als auch der Kunde Zugriff

**Comment by djfhe** [comment]
Sollte nochmal gemeinsam mit @PhilippFaber geschätzt werden

**Comment by PhilippFaber** [comment]
Wir benötigen für diese Aufgabe weitere ecr-Adressen für die Container von andrena sowie eine zusätzliche Datenbank-Instanz.

Ich muss im Jenkins die Container dynamisch benennen, basierend auf dem Branch den passenden Tag/das Ziel auswählen.
Ich gehe davon aus dass beide Systeme auf dem gleichen Server laufen, das bringt zusätzlich das Problem, dass wir den Port dynamisch setzen müssen.

**Comment by PhilippFaber** [comment]
Deployment abgeschlossen und funktioniert
Auf den Staging-Server wird der master-branch, auf den Test-Server der dev-Branch deployed.
Staging besitzt einen eigenen oauth-Zugang, der auf Mitarbeiter von andrena beschränkt ist.
Damit sind alle Anforderungen abgeschlossen
