### ISSUE TITLE
Exploratives Testen

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#127]
Verschiedene Szenarien manuell Testen. Siehe hierzu [Atlassian Exploratives Testen](https://www.atlassian.com/de/continuous-delivery/software-testing/exploratory-testing).
[Testtouren siehe hier](https://produkt-manager.net/2011/exploratory-testing-weitere-testtouren/)
Ggf. auch weitere Issues anlegen/in dailies verteilen.

Testtouren, die durchgeführt werden:

- [x] Museum Tour
- [x] Test one get one free Tour
- [x] Bad Neighbourhood Tour
- [x] Garbage Collector Tour
- [x] Collector’s Tour
- [x] Antisocial Tour
- [x] Supermodel Tour

**Comment by PhilippFaber** [comment]
Bei den Testtouren wurden folgende Fehler gefunden:

Museum Tour:
- Material icons werden lokal gehostet, aber die Auflösung ist nicht gut und die Icons werden jetzt nicht korrekt dargestellt
- Beschriftung verschiedener Knöpfe falsch geschrieben
- Gebäude können gelöscht werden, obwohl es Stockwerke gibt, die eine Buchung haben

Test one get one free Tour
- Wenn man in einem Browserfenster bucht und danach in einem anderen Fenster die gleichen Plätze bucht, ist das ohne Probleme möglich (überprüfung scheint nicht zu funktionieren)
- Lognachrichten in Buchungsübersicht entfernen

Bad Neighbourhood Tour
- Buchung für halben Tag schließt Buchung für andere Tageshälfte aus (weil Vormittags = 8-12 und Nachmittags = 12-16, vielleicht Preset anders konfigurieren)
- Buchungsfenster aktualisiert nicht immer, wenn man ein Datum selektiert. (weil das Datumsfeld noch eine zweite Eingabe für einen Zeitraum erwartet)

Supermodel Tour
Buchungen
- Mobile Ansicht: Buchungsübersicht, Anzeige von Auswahlfeldern könnte über gesamte Bildschirmbreite gehen
- Mobile Ansicht: Warum gibt es zwei Möglichkeiten, die Zeit einzustellen?
- Mobile Ansicht: Buttons um Buchung zu bestätigen/Zeit einzustellen, sehr groß
- Allgemein: Der Button im Toast für Bestätigungen/Fehler hat nicht die korrekte Farbe (rosa statt grün)

Buchungsübersicht:

- Mobile Ansicht: Von/Bis-Daten untereinander schreiben, ist übersichtlicher
- Mobile Ansicht: Darstellung des Raumplanes zu klein

**Comment by PhilippFaber** [comment]
Beide Punkte in neuem Issue ausgelagert

**Comment by PhilippFaber** [comment]
Da alle Bugs, die hier gefunden wurden, gefixed sind, wird die Aufgabe nun geschlossen :)
