### ISSUE TITLE
Farbschema und Logo der Anwendung

### ISSUE THREAD

**Issue by PhilippFaber** [re-place/replace-app#13]
Für die Anwendung und als Repräsentation des Teams wird ein Logo benötigt.
Das Logo soll den Namen der Anwendung einbinden und eine zweite Version besitzen, die als Titelicon in der Anwendung verwendet werden kann.

Zusätzlich soll eine einheitliche Darstellung innerhalb der Anwendung aufgebaut werden. Dafür soll zusätzlich zu dem Logo ein Farbschema gewählt werden, welches sich aus den bekannten Komponenten einer Primärfarbe sowie einer Sekundärfarbe zusammensetzt.

Das aktuell verwendete andrena Logo wird durch das re:Place Logo ersetzt.

Dieses Theme wird zentral im Frontend eingebunden, damit es in der gesamten Anwendung durchgehend verwendet werden kann.

**Comment by djfhe** [comment]
Dazu sollte Rouven gefragt werden, ob andrena über einen entsprechenden Styleguide verfügt. Mindestens primärfarben uund sekundärfarben + shades sollten wir von denen bekommen können.

**Comment by PhilippFaber** [comment]
Jepp, hab ich auch schon auf dem Zettel für Freitag
Bezüglich Logo versuche ich eine erste Idee bis Freitag fertig zu bekommen

**Comment by PhilippFaber** [comment]
Update:
Es existiert kein Style-Guilde von andrena, an den wir uns halten müssen. Allerdings empfiehlt es sich, die Anwendung in Farben zu gestalten, die bereits in internen Anwendungen auftauchen. Hier bietet sich das Grün sowie das Blau an, welche auch schon im Logo zu sehen sind. Diese Farben sollen als Primärfarbe und Sekundärfarbe in der Anwendung eingebunden werden.

Wenn das Logo erstellt wurde, dann wird das endgültige Farbschema erstellt und in Tailwind bzw. Angular Material eingebunden. Auch über die Implementierung eines DarkMode ist zu sprechen.
