### ISSUE TITLE
Booking with past time possible

### ISSUE THREAD

**Issue by Zapzarapza** [re-place/replace-app#133]
Bei einer späteren Uhrzeit (bspw. 13 Uhr) am gleichen Tag ist es über die "einfache" Datum- und Zeitauswahl möglich eine Reservierung zu erstellen, die vormittags (08-12) am selben Tag ist.

![grafik](https://user-images.githubusercontent.com/20536444/223501551-daef5627-b261-4b64-9800-d29d4531e14e.png)

Im Bild ist zu sehen, dass um 13 Uhr eine Buchung eines Arbeitsplatzes von 08 - 12 Uhr erfolgreich getätigt werden kann.

**Comment by PhilippFaber** [comment]
Fixed as it is intended behaviour
