### ISSUE TITLE
Layouting-Fehler

### ISSUE THREAD

**Issue by PhilippFaber** [re-place/replace-app#142]
Allgemeines Issue für fehler im Layout, die in den Testtouren in #127 gefunden wurden.

Folgende Punkte wurden gefunden und sind abzuarbeiten:

Buchungen:
- [x] Mobile Ansicht: Buchungsübersicht, Anzeige von Auswahlfeldern könnte über gesamte Bildschirmbreite gehen
- [x] Mobile Ansicht: Warum gibt es zwei Möglichkeiten, die Zeit einzustellen?
- [x] Mobile Ansicht: Buttons um Buchung zu bestätigen/Zeit einzustellen, sehr groß
- [x] Allgemein: Der Button im Toast für Bestätigungen/Fehler hat nicht die korrekte Farbe (rosa statt grün)

Buchungsübersicht:
- [x] Mobile Ansicht: Von/Bis-Daten untereinander schreiben, ist übersichtlicher
- [x] Mobile Ansicht: Darstellung des Raumplanes zu klein

Allgemein:
- [x] Beschriftung von Buttons überprüfen, diese sind teilweise klein geschrieben.

**Comment by djfhe** [comment]
Zu

> Mobile Ansicht: Warum gibt es zwei Möglichkeiten, die Zeit einzustellen?

Der Button ist noch zusätzlich unten rechts, um eine bessere Erreichbarkeit mit dem Daumen zu erzielen.

**Comment by djfhe** [comment]
https://github.com/re-place/replace-app/pull/154
