### ISSUE TITLE
Fehler in Buchungsübersicht

### ISSUE THREAD

**Issue by PhilippFaber** [re-place/replace-app#143]
In den Testtouren aus #127 wurden verschiedene Fehler im Buchungsprozess gefunden:

- [x] Buchung für halben Tag schließt Buchung für andere Tageshälfte aus (weil Vormittags = 8-12 und Nachmittags = 12-16, vielleicht Preset anders konfigurieren)
- [x] Buchungsfenster aktualisiert nicht immer, wenn man ein Datum selektiert. (weil das Datumsfeld noch eine zweite Eingabe für einen Zeitraum erwartet)
- [x] Wenn man in einem Browserfenster bucht und danach in einem anderen Fenster die gleichen Plätze bucht, ist das ohne Probleme möglich (überprüfung scheint nicht zu funktionieren)

**Comment by PhilippFaber** [comment]
Wenn man in der erweiterten Ansicht im Auswahlfeld fürs Datum ist, kann man ja nicht nur ein spezifisches Datum selektieren, sondern einen gesamten Zeitraum.
Sollte man dennoch nur einen spezifischen Tag auswählen wollen und schließt die Datumsauswahl, nachdem man ein Datum selektiert hat, so aktualisiert sich das Datum nicht, weil es noch einen weiteren Input erwartet.
Es wäre praktisch das Datum jedes mal zu aktualisieren, wenn man das Auswahlfenster schließt.

**Comment by djfhe** [comment]
HAAAAAAAAAAAAAAAAAAA, ich weiß was du meinst. weil er in der erweiterten Ansicht eigentlich ein range will und deine Datums auswahl mit nur einem Klick nicht abgeschlossen ist, da du "nur" das startdatum ausgewählt hast.

**Comment by PhilippFaber** [comment]
Exactly
Kann man das so ändern, dass das Datum als Einzelwert gespeichert wird, wenn man das Feld verlässt?

**Comment by PhilippFaber** [comment]
Der zusätzliche Knopf für die Zeit in der mobilen Ansicht soll noch inaktiv sein, wenn der User keinen Standort/Stockwerk ausgewählt hat.
