### ISSUE TITLE
Fehler im Admin-Bereich

### ISSUE THREAD

**Issue by PhilippFaber** [re-place/replace-app#144]
In den Testtouren aus #127 wurden folgende Fehler im Admin-Bereich gefunden:

- [x] Gebäude können gelöscht werden, obwohl es Stockwerke gibt, die eine Buchung haben
- [x] Etagen können gelöscht werden, obwohl es Buchbare Objekte mit Buchungen gibt
- [x] Wenn man ein Stockwerk speichert, wird man nicht auf die Standortübersicht geleitet.
- [x] Wenn man einen Standort speichert, wird man nicht auf die entsprechende Übersicht geleitet.

Diese Fehler sollen, wenn möglich, noch gelöst werden

**Comment by djfhe** [comment]
Löschen von Gebäuden, Etagen haben wir glaube ich absichtlich erlaubt. Buchungen sollten hierbei mit geschlöscht werden.

Willst du bei einem Update wieder auf den index geleitet werden? Denke das ist eher behavior und kein Bug.

**Comment by PhilippFaber** [comment]
Ja das sollte behavior sein...
Man sollte mMn nach dem Speichern eines Stockwerkes auf die Stockwerksverwaltung geleitet werden und nach dem Speichen des Standortes auf die Standortübersicht. Ansonsten gibt es keine Möglichkeit zurückzugehen.

**Comment by djfhe** [comment]
Should be fixed byhttps://github.com/re-place/replace-app/pull/154
