### ISSUE TITLE
Session-Management in Buchungsübersicht

### ISSUE THREAD

**Issue by PhilippFaber** [re-place/replace-app#153]
Buchen:
- [ ] Mobile Ansicht: Error-Bar "keine Standorte gefunden" wird beim Start einer neuen Session geworfen
- [ ] Mobile Ansicht: Bei einer neuen Session ruft der auswählbare Zeit-Button nicht das Zeit-/Datum-Fenster auf.

https://user-images.githubusercontent.com/20536444/225719842-3f84b340-41d7-41e5-a30f-3a682bc7b259.mov

_Originally posted by @Zapzarapza in https://github.com/re-place/replace-app/issues/127#issuecomment-1472539574_

**Comment by Zapzarapza** [comment]
- [ ] Mit einer neuen Session kann man nach einem ausgewählten Standort den Standort nicht erneut ändern, ohne vorher nicht ein Stockwerk ausgewählt zu haben.

https://user-images.githubusercontent.com/20536444/225724529-5d68be21-a2f7-40e0-af75-33e73e996a1b.mov

**Comment by djfhe** [comment]
https://github.com/re-place/replace-app/pull/154
