### ISSUE TITLE
Zeitraum auswählen führt zu einem merkwürdigen Zwischenstand.

### ISSUE THREAD

**Issue by Zapzarapza** [re-place/replace-app#155]
- [ ] Wählt man im "Erweitert" und wählt nur ein Datum aus, entsteht beim wechsel zwischen "erweitert" und "einfach" einen Zwischenstand, indem beim Datum gesprungen wird.

https://user-images.githubusercontent.com/20536444/225732459-609032da-8580-4c82-bbbf-bd9cbb918a3b.mov

**Comment by djfhe** [comment]
Should be fixed by https://github.com/re-place/replace-app/pull/154
