### ISSUE TITLE
Grafische Grundfläche mit Sitzplatzauswahl

### ISSUE THREAD

**Issue by rroehrig** [re-place/replace-app#38]
Als Benutzer,
möchte ich anstelle einer Liste, auf einer grafischen Grundfläche einen Platz auswählen können.
damit ich schneller einen geeigneten Arbeitsplatz finden kann.

AK

- [x] Wenn ich in den Buchungsprozess gehe, sehe ich den Grundriss der Bürofläche.
- [x] Auf der Bürofläche werden die verfügbaren Arbeitsplätze angezeigt.
- [x] Die Arbeitsplätze sind auf der grafischen Oberfläche Auswählbar

Annahmen:
* Grundriss-Datei ist hinterlegt.
* Arbeitsplätze haben zugewiesene Koordinaten
* OpenLayers ist bereits vorhanden und kann genutzt werden.

**Comment by djfhe** [comment]
Blocked by #44

**Comment by djfhe** [comment]
Closed by #100
