### ISSUE TITLE
Festlegen von buchbaren Arbeitsplätzen

### ISSUE THREAD

**Issue by PhilippFaber** [re-place/replace-app#44]
Als Admin möchte ich auf einem Grundriss festlegen können, wo sich die buchbaren Arbeitsplätze befinden, damit im Buchungsprozess spezifische Arbeitsplätze gebucht werden können. 

Akzeptanzkriterien:

- [ ] Man kann auf einem vorher hochgeladenen Grundriss Arbeitsplätze definieren.
- [ ] Die Arbeitsplätze werden in der Datenbank mit Informationen zu dem Grundriss und der relativen Position korrekt abgelegt.
- [ ] Im Buchungsprozess kann der definierte Arbeitsplatz eingesehen werden und für eine Buchung ausgewählt werden.

**Comment by djfhe** [comment]
Arbeitsplatz Editierung

https://user-images.githubusercontent.com/44621469/216472021-fb6225e4-844a-416b-8c7f-67ea85197e74.mp4
