### ISSUE TITLE
Anzeige von Grundrissen im Buchungsprozess

### ISSUE THREAD

**Issue by PhilippFaber** [re-place/replace-app#57]
Als User 
möchte ich die Grundrisse, die im Backend abgelegt werden, im Buchungsprozess angezeigt bekommen, 
damit ich sehen kann, wo der Arbeitsplatz liegt, den ich buchen möchte.

- [ ] Nach dem Anlegen eines neuen Grundrisses kann ein Nutzer innerhalb des Buchungsprozesses auf den Grundriss zugreifen.
- [ ] Der abgelegte Grundriss für ein Stockwerk wird im Buchungsprozess angezeigt

**Comment by djfhe** [comment]
Done in b27b27ad862da821ee6a1120d01ea4dbe8e0544c
