### ISSUE TITLE
Buchungsvorgang

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#6]
Initiale Prozessimplementierung einer Buchung. Hierzu gehört:
- Auswahl vom Büro
- Auswahl von Stockwerken
- Auswahl von Datum
- Auswahl von Bürofläche
- Buchen

Es müssen also die Modelle
- Büro
- Stockwerk
- Bürofläche
- Reservierung

implementiert werden.

UI, UX ist hier unwichtig, Priorität hat die Implementierung des Buchungsvorgangs.

**Comment by PhilippFaber** [comment]
Im Buchungsvorgang sollen zuerst folgende Dinge ausgewählt werden können:

- Büro
- Stockwerk
- Datum

Darauffolgend soll eine Anzeige erscheinen, die das Büro abbildet und die Auswahl eines spezifischen Arbeitsplatzes ermöglicht.

Nachdem der Arbeitsplatz ausgewählt wurde, soll noch eine Zusammenfassung der Buchung sowie eine Bestätigung erfolgen, danach wird die Buchung im Backend gespeichert.

Im Backend werden dafür die oben genannten Modelle benötigt. Zusätzlich werden Endpoints für die Speicherung einer Reservierung sowie die einzelnen Büros, Stockwerke etc. benötigt, damit man in der Übersicht eines Stockwerkes auch sehen kann, welche Plätze zu einem bestimmten Datum verfügbar sind.

**Comment by PhilippFaber** [comment]
Done by Issues
#34 
#36 
#37 
#38

Aufgabe wird geschlossen
