### ISSUE TITLE
Anzeige von eigenen Reservierungen

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#7]
Als Nutzer 
möchte ich meine getätigten Reservierungen einsehen können, 
damit ich die Details der einzelnen Reservierungen einsehen kann. 
Hierzu benötige ich eine Übersicht über alle von mir getätigten Reservierungen.
    
Akzeptanzkriterien:

- [x] Die Zukünftigen & aktuellen Reservierungen sind in einer Übersicht sichtbar
- [x] In der Übersicht sind nur meine eigenen Reservierungen mit grundlegenden Informationen (Zeitraum, Ort) sichtbar
- [x] Die Übersicht ist über die Navigation aufrufbar
- [x] Die Reservierungen sind nach Startdatum aufsteigend sortiert

**Comment by PhilippFaber** [comment]
Übersichtsseite der bereits getätigten Reservierungen basierend auf einem Nutzer.

Das Backend sollte einen Endpoint bereitstellen, in dem es basierend auf dem Nutzer möglich ist, alle Reservierungen zurückzubekommen.
