### ISSUE TITLE
Rollensystem für User und Admin

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#8]
Wir haben 2 verschiedene Rollen für User:
- Normaler User
- Admin

Rollensysteme sollte im Backend implementiert werden + Entsprechende Route protection.

**Comment by PhilippFaber** [comment]
Im Rollensystem muss auch noch entschieden werden, ob ein Admin auch Userrechte erhält oder ob der Admin eine gänzlich separierte Rolle in unserem System wird.
Für die Verwendung in Zusammenhang mit OAuth ist eine Kombinierung der Rechte einfacher, da so eine eindeutige Rolle für jeden Nutzer existiert.
