### ISSUE TITLE
Admin Bereich

### ISSUE THREAD

**Issue by djfhe** [re-place/replace-app#9]
Admin Bereich mit Placeholdern für Büro CRUD/Stockwerk CRUD.

**Comment by PhilippFaber** [comment]
Im Adminbereich soll vor allem das Anlegen von Büros mit Stockwerken möglich sein. Zusätzlich soll eine Funktionalität geschaffen werden, einen Grundriss eines Stockwerkes zu erstellen.

Diese Funktionalitäten müssen im Backend gespeichert werden können.
